# Generated by Django 4.0.1 on 2022-02-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
