# Generated by Django 4.0.1 on 2022-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_type_message_mtype_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lastdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
