# Generated by Django 4.0.1 on 2022-02-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_lastdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mfile',
            field=models.FileField(null=True, upload_to='go'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
