# Generated by Django 4.0.1 on 2022-02-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_mfile_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='okundu',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mfile',
            field=models.FileField(blank=True, null=True, upload_to='go'),
        ),
    ]
